name: GPSOpenClTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: cmake -S . -B ./build
    - name: make
      run: cd build && make
    - name: move to Test folder and run Test
      run: cd build/Test && ./GPSOpenClTest
