name: GPSOpenClTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v1
    - name: Install Build Essential
      run: sudo apt-get install build-essential ocl-icd-opencl-dev libgtest-dev
    - name: configure
      run: cmake -S . -B ./build
    - name: make
      run: cd build && make
    - name: move to Test folder and run Test
      run: cd build/Test && ./GPSOpenClTest
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v1
      if: always()
      with:
        files: build/Test/TestResult.xml
