name: GPSOpenClTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v1
    - name: Install Build Essential
      run: sudo apt-get install build-essential
    - name: Install clFFT
      run: sudo apt-get install libclfft2 clfft-client libclfft-dev
    - name: Install Qt
      run: sudo apt install g++ qtbase5-dev libqt5svg5-dev qtmultimedia5-dev qtwebengine5-dev libhunspell-dev pkg-config libqt5concurrent5 qttools5-dev-tools
    - name: configure
      run: cmake -S . -B ./build
    - name: make
      run: cd build && make
    - name: move to Test folder and run Test
      run: cd build/Test && ./GPSOpenClTest
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v1
      if: always()
      with:
        files: build/Test/TestResult.xml
